name: CI/CD to EC2
on:
  push:
    branches: [ develop, uat, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4

      - name: Set env
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then echo "env=dev" >> $GITHUB_OUTPUT; fi
          if [[ "${{ github.ref_name }}" == "uat" ]]; then echo "env=uat" >> $GITHUB_OUTPUT; fi
          if [[ "${{ github.ref_name }}" == "main" ]]; then echo "env=prod" >> $GITHUB_OUTPUT; fi

      - name: Deploy
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "$DEPLOY_SSH_KEY" > deploy_key
          chmod 600 deploy_key
          IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=myapp-${{ steps.set-env.outputs.env }}" "Name=instance-state-name,Values=running" --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          scp -i deploy_key app/index.html ubuntu@$IP:/tmp/index.html
          ssh -i deploy_key ubuntu@$IP "sudo mv /tmp/index.html /var/www/html/index.html && sudo systemctl restart apache2"
